# -*- coding: utf-8 -*-
"""topsis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LobUE1eMrSu_ADoKTdO6bKEDeExCnKMH
"""

import sys
import numpy as np
import pandas as pd

def topsis(matrix, weights, impacts):
    matrix = np.array(matrix, dtype=float)
    weights = np.array(weights, dtype=float)

    norm = np.sqrt((matrix ** 2).sum(axis=0))
    normalized = matrix / norm
    weighted = normalized * weights

    ideal_best = []
    ideal_worst = []

    for i in range(len(impacts)):
        if impacts[i] == "+":
            ideal_best.append(weighted[:, i].max())
            ideal_worst.append(weighted[:, i].min())
        else:
            ideal_best.append(weighted[:, i].min())
            ideal_worst.append(weighted[:, i].max())

    ideal_best = np.array(ideal_best)
    ideal_worst = np.array(ideal_worst)

    dist_best = np.sqrt(((weighted - ideal_best) ** 2).sum(axis=1))
    dist_worst = np.sqrt(((weighted - ideal_worst) ** 2).sum(axis=1))

    scores = dist_worst / (dist_best + dist_worst)
    ranks = scores.argsort()[::-1] + 1

    return scores, ranks


def main():
    if len(sys.argv) != 5:
        print("Usage: python topsis.py <inputFile> <weights> <impacts> <outputFile>")
        sys.exit(1)

    input_file = sys.argv[1]
    weights = sys.argv[2].split(",")
    impacts = sys.argv[3].split(",")
    output_file = sys.argv[4]

    try:
        df = pd.read_csv(input_file)
    except FileNotFoundError:
        print("Error: Input file not found")
        sys.exit(1)

    if df.shape[1] < 3:
        print("Error: Input file must contain at least 3 columns")
        sys.exit(1)

    try:
        data = df.iloc[:, 1:].astype(float).values
    except:
        print("Error: Non-numeric values found in criteria columns")
        sys.exit(1)

    if len(weights) != len(impacts) or len(weights) != data.shape[1]:
        print("Error: Number of weights, impacts and criteria must be equal")
        sys.exit(1)

    for i in impacts:
        if i not in ['+', '-']:
            print("Error: Impacts must be either + or -")
            sys.exit(1)

    scores, ranks = topsis(data, weights, impacts)

    df["Topsis Score"] = scores
    df["Rank"] = ranks

    df.to_csv(output_file, index=False)
    print("Result saved to", output_file)


if __name__ == "__main__":
    main()